version: "3.9"
services:
  dashboard:
    build: ./apps/dashboard-server
    environment:
      DASHBOARD_PORT: 4173
      REPORT_PATH: /app/data/last-report.json
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    volumes:
      - ./packages/data:/app/data:ro
      - ./packages/dashboard/dist:/app/dist:ro
    expose: [ "4173" ]
  support:
    build: ./apps/support
    environment:
      SUPPORT_PORT: 3002
      DATA_DIR: /app/var/data
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    volumes:
      - ./var/data:/app/var/data
    expose: [ "3002" ]
  billing:
    build: ./apps/billing
    environment:
      BILLING_PORT: 3003
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-}
      STRIPE_PRICE_ID: ${STRIPE_PRICE_ID:-}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-}
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL:-https://your-domain.example}
    volumes:
      - ./private:/app/private
    expose: [ "3003" ]
  caddy:
    image: caddy:alpine
    ports: [ "80:80", "443:443" ]
    environment:
      DOMAIN: ${DOMAIN:-your-domain.example}
    volumes:
      - ./ops/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - dashboard
      - support
      - billing
volumes:
  caddy_data:
  caddy_config:
