version: "3.9"
services:
  dashboard:
    build: ./apps/dashboard-server
    environment:
      DASHBOARD_PORT: 4173
      REPORT_PATH: /app/data/last-report.json
    ports: [ "4173:4173" ]
    volumes:
      - ./packages/data:/app/data:ro
      - ./packages/dashboard/dist:/app/dist:ro
  support:
    build: ./apps/support
    environment:
      SUPPORT_PORT: 3002
      DATA_DIR: /app/var/data
    ports: [ "3002:3002" ]
    volumes:
      - ./var/data:/app/var/data
  meta:
    build: ./apps/meta
    environment:
      PORT: 3001
    ports: [ "3001:3001" ]
