/* TokPulse — © Hardonia. MIT. */
name: Feature request
description: Propose an enhancement
title: "[Feat] "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: What problem does this solve?
    validations: { required: true }
