name: Auto Unzip TokPulse Scaffold
on:
  push:
    branches: [ main ]
    paths:
      - 'TokPulse_scaffold*.zip'
permissions:
  contents: write
jobs:
  unzip:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[autounzip]')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: sudo apt-get update && sudo apt-get install -y unzip
      - id: pick
        shell: bash
        run: |
          set -euo pipefail
          ZIP="$(ls -t TokPulse_scaffold*.zip | head -n1)"
          if [[ -z "${ZIP:-}" ]]; then
            echo "No TokPulse_scaffold zip found." >&2
            exit 1
          fi
          echo "zip=${ZIP}" >> "$GITHUB_OUTPUT"
      - name: Unzip scaffold into repo root
        run: unzip -o "${{ steps.pick.outputs.zip }}" -d .
      - name: Commit unzipped contents
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "feat(tokpulse): auto-unzip scaffold [autounzip]" || echo "No changes to commit"
          git push
