name: Nightly Backup
on:
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch: {}
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - name: Archive important dirs
        run: |
          mkdir -p backup
          [ -d packages/feedback/data ] && cp -r packages/feedback/data backup/data || true
          [ -d marketing ] && cp -r marketing backup/marketing || true
          zip -r backup.zip backup
      - uses: actions/upload-artifact@v4
        with:
          name: nightly-backup-${{ github.run_id }}
          path: backup.zip
