name: Pages
on:
  push: { branches: [ main ], paths: [ 'docs/site/**' ] }
permissions: { contents: read, pages: write, id-token: write }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with: { path: 'docs/site' }
      - uses: actions/deploy-pages@v4
