name: TokPulse Promote
on:
  workflow_dispatch:
    inputs:
      package_dir:
        description: 'Package dir to promote (e.g., packages/feedback)'
        required: true
jobs:
  promote:
    runs-on: ubuntu-latest
    permissions: {contents: write}
    steps:
      - uses: actions/checkout@v4
        with: {token: ${{ secrets.GITHUB_TOKEN }}}
      - name: Promote
        run: |
          echo "${{ inputs.package_dir }}" > packages/.current
          git config user.name "tokpulse-bot"
          git config user.email "bot@users.noreply.github.com"
          git add packages/.current
          git commit -m "chore: promote -> ${{ inputs.package_dir }}" || echo "No changes"
          git push
      - name: Notify
        run: bash scripts/notify.sh "Promoted to ${{ inputs.package_dir }}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
