name: TokPulse Promote

on:
  workflow_dispatch:
    inputs:
      package_dir:
        description: "Path like packages/<drop-name>"
        required: true
        type: string
      deploy_prod:
        description: "Trigger deploy hooks after promotion?"
        required: true
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate package_dir
        id: validate
        shell: bash
        run: |
          set -euo pipefail
          PD="${{ inputs.package_dir }}"
          if [[ "$PD" != packages/* ]]; then
            echo "package_dir must start with 'packages/'" >&2
            exit 1
          fi
          if [ ! -d "$PD" ]; then
            echo "Path not found: $PD" >&2
            exit 1
          fi
          echo "ok=1" >> "$GITHUB_OUTPUT"

      - name: Write packages/.current
        if: steps.validate.outputs.ok == '1'
        shell: bash
        run: |
          echo "${{ inputs.package_dir }}" > packages/.current
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add packages/.current
          git commit -m "promote: ${{ inputs.package_dir }}" || echo "No changes."
          git push || true

      - name: Trigger Vercel prod deploy (optional)
        if: inputs.deploy_prod && env.VERCEL_HOOK_PROD != ''
        env:
          VERCEL_HOOK_PROD: ${{ secrets.VERCEL_HOOK_PROD }}
        run: |
          curl -sSf -X POST "$VERCEL_HOOK_PROD" && echo "Vercel hook fired."

      - name: Trigger Netlify prod build (optional)
        if: inputs.deploy_prod && env.NETLIFY_HOOK_PROD != ''
        env:
          NETLIFY_HOOK_PROD: ${{ secrets.NETLIFY_HOOK_PROD }}
        run: |
          curl -sSf -X POST -d '{}' "$NETLIFY_HOOK_PROD" && echo "Netlify hook fired."
