/* TokPulse — © Hardonia. MIT. */

name: TokPulse Promote

on:
  workflow_dispatch:
    inputs:
      package_dir:
        description: 'packages/<drop-name>'
        required: true
        type: string
      deploy_prod:
        description: 'Trigger Vercel/Netlify hooks (if secrets set)'
        required: false
        default: true
        type: boolean

permissions:
  contents: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Write packages/.current
        run: |
          echo "${{ github.event.inputs.package_dir }}" > packages/.current
          cat packages/.current
      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add packages/.current
          git commit -m "promote: ${{ github.event.inputs.package_dir }}" || echo "No changes"
          git push || true
      - name: Trigger Vercel Prod Hook
        if: ${{ inputs.deploy_prod == true }}
        env:
          HOOK: ${{ secrets.VERCEL_HOOK_PROD }}
        run: |
          if [ -n "${HOOK:-}" ]; then
            curl -sS -X POST "$HOOK" || true
          else
            echo "VERCEL_HOOK_PROD not set; skipping"
          fi
      - name: Trigger Netlify Prod Hook
        if: ${{ inputs.deploy_prod == true }}
        env:
          HOOK: ${{ secrets.NETLIFY_HOOK_PROD }}
        run: |
          if [ -n "${HOOK:-}" ]; then
            curl -sS -X POST "$HOOK" || true
          else
            echo "NETLIFY_HOOK_PROD not set; skipping"
          fi
