name: TokPulse Run (prefer .current; fallback packages/feedback)
on:
  workflow_dispatch: {}
  push:
    paths:
      - 'packages/**'
      - 'packages/.current'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - name: Determine package target
        id: t
        run: |
          if [ -s packages/.current ]; then
            echo "pkg=$(cat packages/.current)" >> $GITHUB_OUTPUT
          else
            echo "pkg=packages/feedback" >> $GITHUB_OUTPUT
          fi
      - uses: actions/setup-node@v4
        with: {node-version: '20'}
      - name: Install & Build
        working-directory: ${{ steps.t.outputs.pkg }}
        run: |
          npm ci || npm install
          npm run build || true
      - name: Zip artifact
        run: |
          mkdir -p dist
          zip -r dist/package.zip "${{ steps.t.outputs.pkg }}" -x '*.git*'
      - uses: actions/upload-artifact@v4
        with:
          name: package-${{ github.sha }}
          path: dist/package.zip
      - name: Post-build Notifications
        run: bash scripts/notify.sh "TokPulse Run completed: ${{ github.sha }}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
